-- Schema generated by dump_db_sql.py on 2026-06-08T09:42:21.834214Z
PRAGMA foreign_keys = ON;

CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);

CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");

CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");

CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");

CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);

CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");

CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");

CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "webapp_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);

CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");

CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");

CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);

CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");

CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);

CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);

CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE "webapp_attendance" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_time" datetime NOT NULL, "status" varchar(20) NOT NULL, "image_data" varchar(100) NULL, "session_id" bigint NOT NULL REFERENCES "webapp_classsession" ("id") DEFERRABLE INITIALLY DEFERRED, "student_id" bigint NOT NULL REFERENCES "webapp_student" ("user_id") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_attendance_student_id_session_id_3502b1ae_uniq" ON "webapp_attendance" ("student_id", "session_id");

CREATE INDEX "webapp_attendance_session_id_7d504f37" ON "webapp_attendance" ("session_id");

CREATE INDEX "webapp_attendance_student_id_8547aa5e" ON "webapp_attendance" ("student_id");

CREATE TABLE "webapp_classsession" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "day_of_week" varchar(10) NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "room" varchar(50) NOT NULL, "course_id" varchar(20) NOT NULL REFERENCES "webapp_course" ("course_code") DEFERRABLE INITIALLY DEFERRED, "lecturer_id" bigint NOT NULL REFERENCES "webapp_lecturer" ("user_id") DEFERRABLE INITIALLY DEFERRED, "module_id" varchar(20) NULL REFERENCES "webapp_module" ("module_code") DEFERRABLE INITIALLY DEFERRED);

CREATE INDEX "webapp_classsession_course_id_c1454353" ON "webapp_classsession" ("course_id");

CREATE INDEX "webapp_classsession_lecturer_id_5c5af3a3" ON "webapp_classsession" ("lecturer_id");

CREATE INDEX "webapp_classsession_module_id_a7e3eece" ON "webapp_classsession" ("module_id");

CREATE TABLE "webapp_course" ("course_code" varchar(20) NOT NULL PRIMARY KEY, "course_name" varchar(255) NOT NULL);

CREATE TABLE "webapp_course_modules" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "course_id" varchar(20) NOT NULL REFERENCES "webapp_course" ("course_code") DEFERRABLE INITIALLY DEFERRED, "module_id" varchar(20) NOT NULL REFERENCES "webapp_module" ("module_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_course_modules_course_id_module_id_7a56e5d6_uniq" ON "webapp_course_modules" ("course_id", "module_id");

CREATE INDEX "webapp_course_modules_course_id_9044a0a6" ON "webapp_course_modules" ("course_id");

CREATE INDEX "webapp_course_modules_module_id_edd4a9c1" ON "webapp_course_modules" ("module_id");

CREATE TABLE "webapp_enrollment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enrollment_date" date NOT NULL, "course_id" varchar(20) NOT NULL REFERENCES "webapp_course" ("course_code") DEFERRABLE INITIALLY DEFERRED, "student_id" bigint NOT NULL REFERENCES "webapp_student" ("user_id") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_enrollment_student_id_course_id_c8776752_uniq" ON "webapp_enrollment" ("student_id", "course_id");

CREATE INDEX "webapp_enrollment_course_id_5320b17f" ON "webapp_enrollment" ("course_id");

CREATE INDEX "webapp_enrollment_student_id_1356e599" ON "webapp_enrollment" ("student_id");

CREATE TABLE "webapp_enrollment_modules" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enrollment_id" bigint NOT NULL REFERENCES "webapp_enrollment" ("id") DEFERRABLE INITIALLY DEFERRED, "module_id" varchar(20) NOT NULL REFERENCES "webapp_module" ("module_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_enrollment_modules_enrollment_id_module_id_5a29fdd4_uniq" ON "webapp_enrollment_modules" ("enrollment_id", "module_id");

CREATE INDEX "webapp_enrollment_modules_enrollment_id_e65ea2f7" ON "webapp_enrollment_modules" ("enrollment_id");

CREATE INDEX "webapp_enrollment_modules_module_id_15550135" ON "webapp_enrollment_modules" ("module_id");

CREATE TABLE "webapp_faceencoding" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "encoding" text NOT NULL CHECK ((JSON_VALID("encoding") OR "encoding" IS NULL)), "updated_at" datetime NOT NULL, "student_id" bigint NOT NULL UNIQUE REFERENCES "webapp_student" ("user_id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "webapp_lecturer" ("user_id" bigint NOT NULL PRIMARY KEY REFERENCES "webapp_user" ("id") DEFERRABLE INITIALLY DEFERRED, "department" varchar(100) NULL);

CREATE TABLE "webapp_lecturer_modules" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lecturer_id" bigint NOT NULL REFERENCES "webapp_lecturer" ("user_id") DEFERRABLE INITIALLY DEFERRED, "module_id" varchar(20) NOT NULL REFERENCES "webapp_module" ("module_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_lecturer_modules_lecturer_id_module_id_57ada109_uniq" ON "webapp_lecturer_modules" ("lecturer_id", "module_id");

CREATE INDEX "webapp_lecturer_modules_lecturer_id_93040834" ON "webapp_lecturer_modules" ("lecturer_id");

CREATE INDEX "webapp_lecturer_modules_module_id_4499e374" ON "webapp_lecturer_modules" ("module_id");

CREATE TABLE "webapp_lecturer_programs" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lecturer_id" bigint NOT NULL REFERENCES "webapp_lecturer" ("user_id") DEFERRABLE INITIALLY DEFERRED, "program_id" varchar(20) NOT NULL REFERENCES "webapp_program" ("program_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_lecturer_programs_lecturer_id_program_id_51e38907_uniq" ON "webapp_lecturer_programs" ("lecturer_id", "program_id");

CREATE INDEX "webapp_lecturer_programs_lecturer_id_ed197e76" ON "webapp_lecturer_programs" ("lecturer_id");

CREATE INDEX "webapp_lecturer_programs_program_id_fe1c4805" ON "webapp_lecturer_programs" ("program_id");

CREATE TABLE "webapp_module" ("module_code" varchar(20) NOT NULL PRIMARY KEY, "module_name" varchar(255) NOT NULL, "description" text NULL);

CREATE TABLE "webapp_program" ("program_code" varchar(20) NOT NULL PRIMARY KEY, "program_name" varchar(255) NOT NULL, "description" text NULL);

CREATE TABLE "webapp_student" ("user_id" bigint NOT NULL PRIMARY KEY REFERENCES "webapp_user" ("id") DEFERRABLE INITIALLY DEFERRED, "program" varchar(100) NULL, "parent_email" varchar(254) NULL, "parent_phone_num" varchar(20) NULL);

CREATE TABLE "webapp_student_modules" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "student_id" bigint NOT NULL REFERENCES "webapp_student" ("user_id") DEFERRABLE INITIALLY DEFERRED, "module_id" varchar(20) NOT NULL REFERENCES "webapp_module" ("module_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_student_modules_student_id_module_id_03f50242_uniq" ON "webapp_student_modules" ("student_id", "module_id");

CREATE INDEX "webapp_student_modules_student_id_642e41bc" ON "webapp_student_modules" ("student_id");

CREATE INDEX "webapp_student_modules_module_id_c3c6aae7" ON "webapp_student_modules" ("module_id");

CREATE TABLE "webapp_student_programs" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "student_id" bigint NOT NULL REFERENCES "webapp_student" ("user_id") DEFERRABLE INITIALLY DEFERRED, "program_id" varchar(20) NOT NULL REFERENCES "webapp_program" ("program_code") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_student_programs_student_id_program_id_db5fd612_uniq" ON "webapp_student_programs" ("student_id", "program_id");

CREATE INDEX "webapp_student_programs_student_id_b5fb9a76" ON "webapp_student_programs" ("student_id");

CREATE INDEX "webapp_student_programs_program_id_3cf24741" ON "webapp_student_programs" ("program_id");

CREATE TABLE "webapp_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "user_type" varchar(10) NOT NULL);

CREATE TABLE "webapp_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "webapp_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_user_groups_user_id_group_id_bfe43b37_uniq" ON "webapp_user_groups" ("user_id", "group_id");

CREATE INDEX "webapp_user_groups_user_id_ee1e77b2" ON "webapp_user_groups" ("user_id");

CREATE INDEX "webapp_user_groups_group_id_80b22ad1" ON "webapp_user_groups" ("group_id");

CREATE TABLE "webapp_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "webapp_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE UNIQUE INDEX "webapp_user_user_permissions_user_id_permission_id_ae444c59_uniq" ON "webapp_user_user_permissions" ("user_id", "permission_id");

CREATE INDEX "webapp_user_user_permissions_user_id_f651c0ea" ON "webapp_user_user_permissions" ("user_id");

CREATE INDEX "webapp_user_user_permissions_permission_id_c689398b" ON "webapp_user_user_permissions" ("permission_id");

