# Generated by Django 5.2 on 2026-04-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programs',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
